
2020-06-27 20:01:07,106 INFO: errors [in app.py:514]
2020-06-27 22:22:55,796 ERROR: Exception on /artists/1 [GET] [in /home/rakotondrabe/.local/lib/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/rakotondrabe/.local/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/rakotondrabe/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/rakotondrabe/.local/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/rakotondrabe/.local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/rakotondrabe/.local/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/rakotondrabe/.local/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 355, in show_artist
    data = list(filter(lambda d: d['id'] == artist_id, [data1, data2, data3]))[0]
IndexError: list index out of range
